backend:
  name: git-gateway
  branch: master
  repo: grshane/mountainwind3

media_folder: static/img
public_folder: /img

collections:
  - name: "services"
    label: "Services"
    folder: "src/team"
    create: true
    slug: "services/{{slug}}"
    fields:
      - { label: 'Template Name', name: 'template', widget: 'hidden', default: 'service' }
      - { label: 'Service', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: 'Template Name', name: 'template', widget: 'hidden', default: 'page' }
      - { label: 'Page Title', name: 'title', widget: 'string' }
      - { label: 'Content', name: 'content', widget: 'markdown'}
  - name: "films"
    label: "Films"
    folder: "src/films"
    create: true
    slug: "films/{{slug}}"
    fields:
      - { label: 'Template Name', name: 'template', widget: 'hidden', default: 'film' }
      - { label: 'Film Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown'}
      - { label: 'Poster Image', name: 'poster_img', widget: 'image', required: false }

